# Generated by Django 4.2.2 on 2023-07-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
