# Generated by Django 4.2.2 on 2023-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="copies",
            field=models.IntegerField(default=0),
        ),
    ]
