# Generated by Django 4.2.2 on 2023-07-11 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="user",
        ),
    ]
