# Generated by Django 4.2.2 on 2023-07-07 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_copies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="copies",
            new_name="number_of_copies",
        ),
    ]
