# Generated by Django 4.2.2 on 2023-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="copy",
            new_name="copie",
        ),
    ]
