# Generated by Django 4.2.2 on 2023-07-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0003_rename_copy_loan_copie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
