# Generated by Django 4.2.2 on 2023-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copie",
            name="is_borrowed",
            field=models.BooleanField(default=False),
        ),
    ]
