# Generated by Django 4.2.2 on 2023-07-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_user"),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copie",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
    ]
