# Generated by Django 4.2.2 on 2023-07-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_rename_copies_book_number_of_copies"),
        ("copies", "0002_copie_is_borrowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="copie",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
    ]
